// AUTO-GENERATED by cdda_chain_test_gen — validates the cultivation mod chain.
// Place this file in the game's tests/ directory, rebuild the test binary
// (cdda_build_start preset='tests'), then run:
//   tests/cata_test.exe "[cultivation]" --mods cultivation --user-dir ./test_user_dir
//
// The test harness creates a REAL world + avatar and loads `cultivation` (plus
// test_data) into it. It grants `cult_jade_slip_menu` to the avatar, activates the item's
// use_action (driving the item -> EOC chain), then asserts an observable
// side-effect the EOC is expected to produce.
#include <vector>
#include "avatar.h"
#include "catch/catch.hpp"
#include "dialogue.h"
#include "game.h"
#include "item.h"
#include "itype.h"
#include "map_helpers.h"
#include "player_helpers.h"
#include "point.h"
#include "talker.h"
#include "type_id.h"

// The item id to grant and activate.
static const itype_id chain_item( "cult_jade_slip_menu" );

// A per-avatar variable your EOC sets via `u_add_var`, e.g.
//   { "u_add_var": "cult_chain_proof", "type": "flag", "context": "chain",
//      "value": "yes" }
// Change this name to match whatever variable your EOC writes.
static const std::string chain_var = "cult_chain_proof";

TEST_CASE( "cultivation/chain-item-eoc-activates", "[cultivation][item]" )
{
    clear_avatar();
    clear_map_without_vision();
    avatar &dummy = get_avatar();

    // 1. grant the item
    item slip( chain_item );
    item_location loc = dummy.i_add( slip );
    REQUIRE( dummy.has_item( *loc ) );

    // record the pre-state of the EOC-side-effect variable (absent => unset)
    bool was_set = dummy.get_value( chain_var ) != "";
    INFO( "chain_var was " << ( was_set ? "already set" : "unset" ) << " before activate" );

    // 2. activate the item's use_action (drives item -> EOC)
    dummy.use( loc );

    // 3. assert the EOC side-effect
    CHECK( dummy.get_value( chain_var ) != "" );
}
